export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const MESSAGE_SEARCH = Symbol('MESSAGE_SEARCH');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
